name: Test

on:
  push:
    branches:
      - master

jobs:
  test-broker:
    name: EMQ [${{ matrix.version }}]
   
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['4.4.1', 'latest']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start EMQ
        uses: ./
        with:
          version: ${{ matrix.version }}
